# Generated by Django 5.1.6 on 2025-02-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento_em_dia', models.BooleanField(default=True)),
                ('queixa', models.CharField(choices=[('TDAH', 'TDAH'), ('D', 'DEPRESSÃO'), ('A', 'ANSIEDADE'), ('TAG', 'TRANSTORNO DE ANSIEDADE GENERALIZADA')], max_length=4)),
            ],
        ),
    ]
