# Generated by Django 5.1.6 on 2025-02-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pacientes',
            name='foto',
            field=models.ImageField(default=True, upload_to='fotos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='nome',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pacientes',
            name='telefone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
